openapi: 3.1.0

info:
  version: 1.0.0
  title: Contacts api
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is documentation of Contacts api

tags:
  - name: Contacts
    description: Operations with contacts

servers:
  - url: http://127.0.0.1:3000

paths:
  /contacts/contactId:
    get:
      $ref: ../swagger/paths/contacts/contactId/get.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
